//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFS.PMS.TaskReminderJob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RemnderMailSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RemnderMailSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VFS.PMS.TaskReminderJob.RemnderMailSettings", typeof(RemnderMailSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1-Appraisee Appeal&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt;             
        /// {3} (Appraisee) has submitted an appeal requesting you to re-evaluate the Appraisal for the period H1, {4}. The current status of the appraisal is &quot;H1-Appraisee Appeal&quot; and you can access  the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;    
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AppraiseeAppeal {
            get {
                return ResourceManager.GetString("H1AppraiseeAppeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - H1 - Awaiting Appraisee Goal Setting %
        ///Remainder: Dear {2}, &lt;br/&gt;&lt;br/&gt;You are requested to set the goals for the period H1, {3}.The current status of the appraisal is &quot;H1 - Awaiting Appraisee Goal Setting&quot; and you can access the appraisal using the link, &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiseeGoalSetting {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiseeGoalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Appraisee Sign-off&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (Reviewer) has approved the evaluation of your appraisal for the period H1, {4} and awaiting your sign-off. The current status of the appraisal is &quot;H1 - Awaiting Appraisee Sign-off&quot; and you can access the appraisal using the link,&lt;a href={5}&gt;{5} &lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiseeSignoff {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiseeSignoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Appraiser Evaluation&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) has submitted Appraisal self-evaluation for the period H1, {5} and awaiting your evaluation.The current status of the appraisal is &quot;H1 - Awaiting Appraiser Evaluation&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiserEvaluation {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiserEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - H1 Awaiting Appraiser Goal Approval %
        ///Dear {2}, &lt;br/&gt;&lt;br/&gt; {3}({4}) (Appraisee) submitted the goals - Appraisal for the period H1, {5} and awaiting your approval. The current status of the appraisal is &quot;H1 Awaiting Appraiser Goal Approval&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiserGoalApproval {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiserGoalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Reviewer Approval&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3}  has submitted the evaluation for H1,{4} Appraisal of {5} ({6}) and awaiting your approval. The current status of the appraisal is &quot;H1 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the link, &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingReviewerApproval {
            get {
                return ResourceManager.GetString("H1AwaitingReviewerApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Self-evaluation&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt;You are requested to complete self-evaluation of your appraisal for the period H1, {3}.The current status of the appraisal is &quot;H1 - Awaiting Self-evaluation&quot; and you can access the appraisal using the link, &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingSelfevaluation {
            get {
                return ResourceManager.GetString("H1AwaitingSelfevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1-Completed&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Your Appraisal for the period H1, {3} is complete and awaiting you to set the goals for H2, {3}. The current status of the appraisal is &quot;H1-Completed&quot; and you can access the appraisal using  the link, &lt;a href={4}&gt;{4}&gt;&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1Completed {
            get {
                return ResourceManager.GetString("H1Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1 - Goals Approved&quot;%
        ///Dear {2}, &lt;br/&gt;&lt;br/&gt; {3} (Appraiser) approved Goals of your appraisal for the period H1, {4} by {5}. The current status of the appraisal is &quot;H1 - Goals Approved&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1GoalsApproved {
            get {
                return ResourceManager.GetString("H1GoalsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1 - HR Review&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (HR) requests you to re-evaluate the Appraisal of {4} for the period H1, {5}. The current status of the appraisal is &quot;H1 - HR Review&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1HRReview {
            get {
                return ResourceManager.GetString("H1HRReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H1, {0} Appraisal - {1} - &quot;H1 - Sign-off by Appraisee&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Appraisal of {3} for the period H1, {4} is awaiting your decision.The current status of the appraisal is &quot;H1 - Sign-off by Appraisee&quot;.You can access the appraisal using  the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1SignoffbyAppraisee {
            get {
                return ResourceManager.GetString("H1SignoffbyAppraisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - &quot;H2-Appraisee Appeal&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt;             
        /// {3} (Appraisee) has submitted an appeal requesting you to re-evaluate the Appraisal for the period H2, {4}. The current status of the appraisal is &quot;H2-Appraisee Appeal&quot; and you can access  the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;    
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AppraiseeAppeal {
            get {
                return ResourceManager.GetString("H2AppraiseeAppeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - H2 - Awaiting Appraisee Sign-off %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (Reviewer) approved the evaluation of your appraisal for the period H2, {4} and awaiting your sign-off. The current status of the appraisal is &quot;H2 - Awaiting Appraisee Sign-off&quot; and you can access the appraisal using the link,&lt;a href={5}&gt;{5} &lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiseeSignoff {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiseeSignoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Evaluation&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) has submitted Appraisal self-evaluation for the period H2, {5} and awaiting your evaluation.The current status of the appraisal is &quot;H2 - Awaiting Appraiser Evaluation&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserEvaluation {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Goal Approval&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) has submitted the goals - Appraisal for the period H2, {5} and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Appraiser Goal Approval&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserGoalApproval {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserGoalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1}- H2 - Awaiting Reviewer Approval%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} has submitted the evaluation for H2,{4} Appraisal of {5} ({6}) and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the link, &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingReviewerApproval {
            get {
                return ResourceManager.GetString("H2AwaitingReviewerApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Self-evaluation&quot;%
        ///Dear  {2},&lt;br/&gt;&lt;br/&gt; You are requested to complete self-evaluation of your appraisal for the period H2, {3}.The current status of the appraisal is &quot;H2 - Awaiting Self-evaluation&quot; and you can access the appraisal using the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingSelfevaluation {
            get {
                return ResourceManager.GetString("H2AwaitingSelfevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - H2-Completed%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Your Appraisal for the period H2, {3} is complete. The current status of the appraisal is &quot;H2-Completed&quot; and you can access the appraisal using the link, &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2Completed {
            get {
                return ResourceManager.GetString("H2Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - &quot;H2 - Goals Approved&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (Appraiser) has approved Goals of your appraisal for the period H2, {4} by {5}. The current status of the appraisal is &quot;H2 - Goals Approved&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2GoalsApproved {
            get {
                return ResourceManager.GetString("H2GoalsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1}- &quot;H2-HR Review&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (HR) requests you to re-evaluate the Appraisal of {4} for the period H2, {5}. The current status of the appraisal is &quot;H2-HR Review&quot; and you can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2HRReview {
            get {
                return ResourceManager.GetString("H2HRReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: H2, {0} Appraisal - {1} - &quot;H2 - Sign-off by Appraisee&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Appraisal of {3} for the period H2, {4} is awaiting your decision.The current status of the appraisal is &quot;H2 - Sign-off by Appraisee&quot; and you can access the appraisal using the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2SignoffbyAppraisee {
            get {
                return ResourceManager.GetString("H2SignoffbyAppraisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Sign-off by Appraisee&quot;%.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {2},&lt;br/&gt;&lt;br/&gt; Appraisal of {3} for the period H1, {4} is awaiting your decision.The current status of the appraisal is &quot;H1 - Sign-off by Appraisee&quot;.You can access the appraisal using  the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regards,&lt;br/&gt;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team - HR&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
    }
}
