//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFS_AppraisalWorkflow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppraisalMailFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppraisalMailFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VFS_AppraisalWorkflow.AppraisalMailFormats", typeof(AppraisalMailFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1-Appraisee Appeal&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt;             
        /// {3} (Appraisee) has submitted an appeal requesting you to re-evaluate the Appraisal for the period H1, {4}. The current status of the appraisal is &quot;H1-Appraisee Appeal&quot;.&lt;br/&gt;&lt;br/&gt;You can access  the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;    
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AppraiseeAppeal {
            get {
                return ResourceManager.GetString("H1AppraiseeAppeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1-Appraisee Appeal&quot; %
        ///Dear {2}, &lt;br/&gt;{3} (Appraisee) submitted the appeal requesting you to re-evaluate the Appraisal for the period H1, {4}. The current status of the appraisal is &quot;H1-Appraisee Appeal&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks &lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AppraiseeAppeal1 {
            get {
                return ResourceManager.GetString("H1AppraiseeAppeal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - H1 - Awaiting Appraisee Goal Setting %
        ///Dear {2}, &lt;br/&gt;&lt;br/&gt;You are requested to set the goals for the period H1, {3}.The current status of the appraisal is &quot;H1 - Awaiting Appraisee Goal Setting&quot;.    &lt;br/&gt; &lt;br/&gt;  You can access the appraisal using the link, &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Regards,&lt;br/&gt;
        ///Team - HR &lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiseeGoalSetting {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiseeGoalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - H1 - Awaiting Appraisee Goal Setting %
        ///Hello {2}, You are requested to set the goals for the period H1, {3}.The current status of the appraisal is &quot;H1 - Awaiting Appraisee Goal Setting&quot; and you can access the appraisal using the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiseeGoalSetting1 {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiseeGoalSetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Appraisee Sign-off&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (Reviewer) has approved the evaluation of your appraisal for the period H1, {4} and awaiting your sign-off. The current status of the appraisal is &quot;H1 - Awaiting Appraisee Sign-off&quot;.You can access the appraisal using the link,&lt;a href={5}&gt;{5} &lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiseeSignoff {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiseeSignoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Appraisee Sign-off&quot; %
        ///Hello {2}, {3} (Reviewer) approved the evaluation of your appraisal for the period H1, {4} and awaiting your sign-off. The current status of the appraisal is &quot;H1 - Awaiting Appraisee Sign-off&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiseeSignoff1 {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiseeSignoff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Appraiser Evaluation&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) has submitted Appraisal self-evaluation for the period H1, {5} and awaiting your evaluation.The current status of the appraisal is &quot;H1 - Awaiting Appraiser Evaluation&quot;.You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiserEvaluation {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiserEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Appraiser Evaluation&quot; %
        ///Hello {2}, {3} ({4}) (Appraisee) submitted Appraisal self-evaluation for the period H1, {5} and awaiting your evaluation.The current status of the appraisal is &quot;H1 - Awaiting Appraiser Evaluation&quot; and you can access the appraisal using the &lt;a href={6}&gt;link, &lt;/a&gt;. &lt;/br&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiserEvaluation1 {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiserEvaluation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - H1 Awaiting Appraiser Goal Approval %
        ///Dear {2}, &lt;br/&gt;&lt;br/&gt; {3}({4}) (Appraisee) submitted the goals - Appraisal for the period H1, {5} and awaiting your approval. The current status of the appraisal is &quot;H1 Awaiting Appraiser Goal Approval&quot;. &lt;br/&gt;&lt;br/&gt;You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiserGoalApproval {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiserGoalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - H1 Awaiting Appraiser Goal Approval %
        ///Hello {2}, {3}({4}) (Appraisee) submitted the goals - Appraisal for the period H1, {5} and awaiting your approval. The current status of the appraisal is &quot;H1 Awaiting Appraiser Goal Approval&quot; and you can access the appraisal using the &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiserGoalApproval1 {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiserGoalApproval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Appraiser Goal Approval&quot;%             Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) amended the goals - Appraisal for the period H1, {5} and awaiting your approval.The current status of the appraisal is &quot;H1 - Awaiting Appraiser Goal Approval&quot;.&lt;br/&gt;&lt;br/&gt; You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingAppraiserGoalApproval21 {
            get {
                return ResourceManager.GetString("H1AwaitingAppraiserGoalApproval21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Reviewer Approval&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3}  has submitted the evaluation for H1,{4} Appraisal of {5} ({6}) and awaiting your approval. The current status of the appraisal is &quot;H1 - Awaiting Reviewer Approval&quot;.You can access the appraisal using the link, &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingReviewerApproval {
            get {
                return ResourceManager.GetString("H1AwaitingReviewerApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Reviewer Approval&quot; %
        ///Hello {2}, {3} submitted the evaluation for H1,{4} Appraisal of {5} ({6}) and awaiting your approval. The current status of the appraisal is &quot;H1 - Awaiting Reviewer Approval&quot; and you can access the appraisal using  the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingReviewerApproval1 {
            get {
                return ResourceManager.GetString("H1AwaitingReviewerApproval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Reviewer Approval&quot; %
        ///Hello {2}, {3} submitted the re-evaluation for H1,{4} Appraisal of {5} ({6}) after appeal by appraisee and awaiting your approval. The current status of the appraisal is &quot;H1 - Awaiting Reviewer Approval&quot; and you can access the appraisal using  the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingReviewerApproval2 {
            get {
                return ResourceManager.GetString("H1AwaitingReviewerApproval2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Reviewer Approval&quot; %
        ///Hello {2}, {3} submitted the re-evaluation for H1,{4} Appraisal of {5} ({6}) after appeal by appraisee and awaiting your approval. The current status of the appraisal is &quot;H1 - Awaiting Reviewer Approval&quot; and you can access the appraisal using  the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingReviewerApproval21 {
            get {
                return ResourceManager.GetString("H1AwaitingReviewerApproval21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Reviewer Approval&quot;&gt;%
        ///Hello {2}, {3} submitted the re-evaluation for H1,{4} Appraisal of {5} ({6}) after review request by HR and awaiting your approval. The current status of the appraisal is &quot;H1 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingReviewerApproval3 {
            get {
                return ResourceManager.GetString("H1AwaitingReviewerApproval3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Reviewer Approval&quot;&gt;%
        ///Hello {2}, {3} submitted the re-evaluation for H1,{4} Appraisal of {5} ({6}) after review request by HR and awaiting your approval. The current status of the appraisal is &quot;H1 - Awaiting Reviewer Approval&quot; and you can access the appraisal using  the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingReviewerApproval31 {
            get {
                return ResourceManager.GetString("H1AwaitingReviewerApproval31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Self-evaluation&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt;You are requested to complete self-evaluation of your appraisal for the period H1, {3}.The current status of the appraisal is &quot;H1 - Awaiting Self-evaluation&quot;.You can access the appraisal using the link, &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingSelfevaluation1 {
            get {
                return ResourceManager.GetString("H1AwaitingSelfevaluation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Self-evaluation&quot; %
        ///Hello {2}, You are requested to complete self-evaluation of your appraisal for the period H1, {3}.The current status of the appraisal is &quot;H1 - Awaiting Self-evaluation&quot; and you can access the appraisal using  the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1AwaitingSelfevaluation11 {
            get {
                return ResourceManager.GetString("H1AwaitingSelfevaluation11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Self-evaluation&quot; %
        ///Hello {2}, You are requested to complete self-evaluation of your appraisal for the period H1, {3}.The current status of the appraisal is &lt;Current Status&gt; and you can access the appraisal using  the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email.&quot;.
        /// </summary>
        internal static string H1AwaitingSelfevaluation2 {
            get {
                return ResourceManager.GetString("H1AwaitingSelfevaluation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Awaiting Self-evaluation&quot; %
        ///Hello {2}, You are requested to complete self-evaluation of your appraisal for the period H1, {3}.The current status of the appraisal is &lt;Current Status&gt; and you can access the appraisal using the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email.&quot;.
        /// </summary>
        internal static string H1AwaitingSelfevaluation21 {
            get {
                return ResourceManager.GetString("H1AwaitingSelfevaluation21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1-Completed&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Your Appraisal for the period H1, {3} is complete and awaiting you to set the goals for H2, {4}. The current status of the appraisal is &quot;H1-Completed&quot;.You can access the appraisal using  the link, &lt;a href={5}&gt;{5}&gt;&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1Completed {
            get {
                return ResourceManager.GetString("H1Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1-Completed&quot; %
        ///Hello {2}, Your Appraisal for the period H1, {3} is complete and awaiting you to set the goals for H2, {4}. The current status of the appraisal is &quot;H1-Completed&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1Completed1 {
            get {
                return ResourceManager.GetString("H1Completed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Goals Approved&quot;%
        ///Dear {2}, &lt;br/&gt;&lt;br/&gt; {3} (Appraiser) approved Goals of your appraisal for the period H1, {4} by {5}. The current status of the appraisal is &quot;H1 - Goals Approved&quot;. &lt;br/&gt;&lt;br/&gt; You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1GoalsApproved {
            get {
                return ResourceManager.GetString("H1GoalsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Goals Approved&quot;%
        ///Hello {2}, {3} (Appraiser) approved Goals of your appraisal for the period H1, {4} by {5}. The current status of the appraisal is &quot;H1 - Goals Approved&quot; and you can access the appraisal using the &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1GoalsApproved1 {
            get {
                return ResourceManager.GetString("H1GoalsApproved1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - HR Review&quot; %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (HR) requests you to re-evaluate the Appraisal of &lt;Appraisee Name&gt; for the period H1, {4}. The current status of the appraisal is &quot;H1 - HR Review&quot;.You can access the appraisal using the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1HRReview {
            get {
                return ResourceManager.GetString("H1HRReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - HR Review&quot; %
        ///Hello {2}, {3} (HR) requests you to re-evaluate the Appraisal of &lt;Appraisee Name&gt; for the period H1, {4}. The current status of the appraisal is &quot;H1 - HR Review&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1HRReview1 {
            get {
                return ResourceManager.GetString("H1HRReview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 Sign Off of by Appraisee&quot; 
        ///
        ///
        ///%  Dear {2},&lt;br/&gt;&lt;br/&gt;  Your Appraisal  for the period H1, {3}has been  Signed Off by your HR Business Partner {4} on behalf of you.The current status of the appraisal is &quot;H1 - Sign-off by Appraisee&quot;.&lt;br/&gt;&lt;br/&gt; You can view the appraisal using the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1HRSignOff {
            get {
                return ResourceManager.GetString("H1HRSignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Sign-off by Appraisee&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Appraisal of {3} for the period H1, {4} is awaiting your decision.The current status of the appraisal is &quot;H1 - Sign-off by Appraisee&quot;.You can access the appraisal using  the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1SignoffbyAppraisee {
            get {
                return ResourceManager.GetString("H1SignoffbyAppraisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Sign-off by Appraisee&quot;%
        ///Hello {2}, Appraisal of {3} for the period H1, {4} is awaiting your decision.The current status of the appraisal is &quot;H1 - Sign-off by Appraisee&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H1SignoffbyAppraisee1 {
            get {
                return ResourceManager.GetString("H1SignoffbyAppraisee1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Sign-off by Appraisee&quot; %
        ///Hello {2}, {3} prescribed Performance Improvement Plan (PIP) based on your performance during the period H1, {4}. The current status of the appraisal is &quot;H1 - Sign-off by Appraisee&quot; and you can access the appraisal using  the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email.&quot;.
        /// </summary>
        internal static string H1SignoffbyAppraisee2 {
            get {
                return ResourceManager.GetString("H1SignoffbyAppraisee2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1, {0} Appraisal - {1} - &quot;H1 - Sign-off by Appraisee&quot; %
        ///Hello {2}, {3} prescribed Performance Improvement Plan (PIP) based on your performance during the period H1, {4}. The current status of the appraisal is &quot;H1 - Sign-off by Appraisee&quot; and you can access the appraisal usingthe &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email.&quot;.
        /// </summary>
        internal static string H1SignoffbyAppraisee21 {
            get {
                return ResourceManager.GetString("H1SignoffbyAppraisee21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2-Appraisee Appeal&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt;             
        /// {3} (Appraisee) has submitted an appeal requesting you to re-evaluate the Appraisal for the period H2, {4}. The current status of the appraisal is &quot;H2-Appraisee Appeal&quot;.&lt;br/&gt;&lt;br/&gt;You can access  the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;    
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AppraiseeAppeal {
            get {
                return ResourceManager.GetString("H2AppraiseeAppeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2-Appraisee Appeal&quot;%
        ///Hello {2}, Appraisal of {3} for the period H2, {4} is awaiting your decision.The current status of the appraisal is &quot;H2-Appraisee Appeal&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AppraiseeAppeal1 {
            get {
                return ResourceManager.GetString("H2AppraiseeAppeal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraisee Goal Setting&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; You are requested to set the goals for the period H2, {3}.The current status of the appraisal is &quot;H2 - Awaiting Appraisee Goal Setting&quot;.You can access the appraisal using the link,&lt;a href={4}&gt;&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiseeGoalSetting {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiseeGoalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraisee Goal Setting&quot;%
        ///Hello {2}, You are requested to set the goals for the period H2, {3}.The current status of the appraisal is &quot;H2 - Awaiting Appraisee Goal Setting&quot; and you can access the appraisal using the &lt;a href={4}&gt;link, &lt;/a&gt;.&lt;/br&gt;
        ///
        ///Thanks&lt;/br&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiseeGoalSetting1 {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiseeGoalSetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - H2 - Awaiting Appraisee Sign-off %
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (Reviewer) approved the evaluation of your appraisal for the period H2, {4} and awaiting your sign-off. The current status of the appraisal is &quot;H2 - Awaiting Appraisee Sign-off&quot;.You can access the appraisal using the link,&lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiseeSignoff {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiseeSignoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - H2 - Awaiting Appraisee Sign-off %
        ///Hello {2}, {3} (Reviewer) approved the evaluation of your appraisal for the period H2, {4} and awaiting your sign-off. The current status of the appraisal is &quot;H2 - Awaiting Appraisee Sign-off&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiseeSignoff1 {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiseeSignoff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Evaluation&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) has submitted Appraisal self-evaluation for the period H2, {5} and awaiting your evaluation.The current status of the appraisal is &quot;H2 - Awaiting Appraiser Evaluation&quot;.You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserEvaluation {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Evaluation&quot;%
        ///Hello {2}, {3} ({4}) (Appraisee) submitted Appraisal self-evaluation for the period H2, {5} and awaiting your evaluation.The current status of the appraisal is &quot;H2 - Awaiting Appraiser Evaluation&quot; and you can access the appraisal using the &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserEvaluation1 {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserEvaluation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Goal Approval&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) has submitted the goals - Appraisal for the period H2, {5} and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Appraiser Goal Approval&quot;.You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserGoalApproval {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserGoalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Goal Approval&quot;%
        ///Hello {2}, {3} ({4}) (Appraisee) submitted the goals - Appraisal for the period H2, {5} and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Appraiser Goal Approval&quot; and you can access the appraisal using the &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserGoalApproval1 {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserGoalApproval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Goal Approval&quot;%
        ///Hello {2}, {3} ({4}) (Appraisee) amended the goals - Appraisal for the period H2, {5} and awaiting your approval.The current status of the appraisal is &quot;H2 - Awaiting Appraiser Goal Approval&quot; and you can access the appraisal using the the &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserGoalApproval2 {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserGoalApproval2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Appraiser Goal Approval&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} ({4}) (Appraisee) amended the goals - Appraisal for the period H2, {5} and awaiting your approval.The current status of the appraisal is &quot;H2 - Awaiting Appraiser Goal Approval&quot;.&lt;br/&gt;&lt;br/&gt; You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingAppraiserGoalApproval21 {
            get {
                return ResourceManager.GetString("H2AwaitingAppraiserGoalApproval21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1}- H2 - Awaiting Reviewer Approval%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} has submitted the evaluation for H2,{4} Appraisal of {5} ({6}) and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Reviewer Approval&quot;.You can access the appraisal using the link, &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingReviewerApproval {
            get {
                return ResourceManager.GetString("H2AwaitingReviewerApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1}- H2 - Awaiting Reviewer Approval%
        ///Hello {2}, {3} submitted the evaluation for H2,{4} Appraisal of {5} ({6}) and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingReviewerApproval1 {
            get {
                return ResourceManager.GetString("H2AwaitingReviewerApproval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Reviewer Approval&quot;%
        ///Hello {2}, {3} submitted the re-evaluation for H2,{4} Appraisal of {5} ({6}) after appeal by appraisee and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingReviewerApproval2 {
            get {
                return ResourceManager.GetString("H2AwaitingReviewerApproval2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Reviewer Approval&quot;%
        ///Hello {2}, {3} submitted the re-evaluation for H2,{4} Appraisal of {5} ({6}) after appeal by appraisee and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingReviewerApproval21 {
            get {
                return ResourceManager.GetString("H2AwaitingReviewerApproval21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Reviewer Approval&quot;%
        ///Hello {2}, {3} submitted the re-evaluation for H2,{4} Appraisal of {5} ({6}) after review request by HR and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingReviewerApproval3 {
            get {
                return ResourceManager.GetString("H2AwaitingReviewerApproval3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Reviewer Approval&quot;%
        ///Hello {2}, {3} submitted the re-evaluation for H2,{4} Appraisal of {5} ({6}) after review request by HR and awaiting your approval. The current status of the appraisal is &quot;H2 - Awaiting Reviewer Approval&quot; and you can access the appraisal using the &lt;a href={7}&gt;{7}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingReviewerApproval31 {
            get {
                return ResourceManager.GetString("H2AwaitingReviewerApproval31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Self-evaluation&quot;%
        ///Dear  {2},&lt;br/&gt;&lt;br/&gt; You are requested to complete self-evaluation of your appraisal for the period H2, {3}.The current status of the appraisal is &quot;H2 - Awaiting Self-evaluation&quot;.You can access the appraisal using the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingSelfevaluation {
            get {
                return ResourceManager.GetString("H2AwaitingSelfevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Awaiting Self-evaluation&quot;%
        ///Hello {2}, You are requested to complete self-evaluation of your appraisal for the period H2, {3}.The current status of the appraisal is &quot;H2 - Awaiting Self-evaluation&quot; and you can access the appraisal using the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2AwaitingSelfevaluation1 {
            get {
                return ResourceManager.GetString("H2AwaitingSelfevaluation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - H2-Completed%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Your Appraisal for the period H2, {3} is complete. The current status of the appraisal is &quot;H2-Completed&quot;.You can access the appraisal using the link, &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2Completed {
            get {
                return ResourceManager.GetString("H2Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - H2-Completed%
        ///Hello {2}, Your Appraisal for the period H2, {3} is complete. The current status of the appraisal is &quot;H2-Completed&quot; and you can access the appraisal using the &lt;a href={4}&gt;{4}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2Completed1 {
            get {
                return ResourceManager.GetString("H2Completed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Goals Approved&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (Appraiser) has approved Goals of your appraisal for the period H2, {4} by {5}. The current status of the appraisal is &quot;H2 - Goals Approved&quot;.You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2GoalsApproved {
            get {
                return ResourceManager.GetString("H2GoalsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Goals Approved&quot;%
        ///Hello {2}, {3} (Appraiser) approved Goals of your appraisal for the period H2, {4} by {5}. The current status of the appraisal is &quot;H2 - Goals Approved&quot; and you can access the appraisal using the &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2GoalsApproved1 {
            get {
                return ResourceManager.GetString("H2GoalsApproved1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Goals Approved&quot;%
        ///Hello {2}, {3} (Appraiser) amended the goals of your appraisal for the period H2, {4}. The current status of the appraisal is &quot;H2 - Goals Approved&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2GoalsApproved2 {
            get {
                return ResourceManager.GetString("H2GoalsApproved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Goals Approved&quot;%
        ///Hello {2}, {3} (Appraiser) amended the goals of your appraisal for the period H2, {4}. The current status of the appraisal is &quot;H2 - Goals Approved&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2GoalsApproved21 {
            get {
                return ResourceManager.GetString("H2GoalsApproved21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1}- &quot;H2-HR Review&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; {3} (HR) requests you to re-evaluate the Appraisal of {4} for the period H2, {5}. The current status of the appraisal is &quot;H2-HR Review&quot;.You can access the appraisal using the link, &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2HRReview {
            get {
                return ResourceManager.GetString("H2HRReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1}- &quot;H2-HR ReviewH2-HR Review&quot;%
        ///Hello {2}, {3} (HR) requests you to re-evaluate the Appraisal of {4} for the period H2, {5}. The current status of the appraisal is &quot;H2-HR ReviewH2-HR Review&quot; and you can access the appraisal using the &lt;a href={6}&gt;{6}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2HRReview1 {
            get {
                return ResourceManager.GetString("H2HRReview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 Sign Off of by Appraisee&quot; 
        ///
        ///
        ///%  Dear {2},&lt;br/&gt;&lt;br/&gt;  Your Appraisal  for the period H2, {3}has been  Signed Off by your HR Business Partner {4} on behalf of you.The current status of the appraisal is &quot;H2 - Sign-off by Appraisee&quot;.&lt;br/&gt;&lt;br/&gt; You can view the appraisal using the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2HRSignOff {
            get {
                return ResourceManager.GetString("H2HRSignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Sign-off by Appraisee&quot;%
        ///Dear {2},&lt;br/&gt;&lt;br/&gt; Appraisal of {3} for the period H2, {4} is awaiting your decision.The current status of the appraisal is &quot;H2 - Sign-off by Appraisee&quot;.You can access the appraisal using the link, &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Regards,&lt;br/&gt;
        ///Team - HR&lt;br/&gt;&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2SignoffbyAppraisee {
            get {
                return ResourceManager.GetString("H2SignoffbyAppraisee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Sign-off by Appraisee&quot;%
        ///Hello {2}, Appraisal of {3} for the period H2, {4} is awaiting your decision.The current status of the appraisal is &quot;H2 - Sign-off by Appraisee&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2SignoffbyAppraisee1 {
            get {
                return ResourceManager.GetString("H2SignoffbyAppraisee1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Sign-off by Appraisee&quot;%
        ///Hello {2}, {3} prescribed Performance Improvement Plan (PIP) based on your performance during the period H2, {4}. The current status of the appraisal is &quot;H2 - Sign-off by Appraisee&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2SignoffbyAppraisee2 {
            get {
                return ResourceManager.GetString("H2SignoffbyAppraisee2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2, {0} Appraisal - {1} - &quot;H2 - Sign-off by Appraisee&quot;%
        ///Hello {2}, {3} prescribed Performance Improvement Plan (PIP) based on your performance during the period H2, {4}. The current status of the appraisal is &quot;H2 - Sign-off by Appraisee&quot; and you can access the appraisal using the &lt;a href={5}&gt;{5}&lt;/a&gt;.&lt;br/&gt;
        ///
        ///Thanks&lt;br/&gt;
        ///
        ///Disclaimer: This is system generated email. Please do not reply to this email..
        /// </summary>
        internal static string H2SignoffbyAppraisee21 {
            get {
                return ResourceManager.GetString("H2SignoffbyAppraisee21", resourceCulture);
            }
        }
    }
}
